#baseurl = "https://www.open-source-modular.org"
baseurl = "https://grand-sundae-ec2188.netlify.app"
DefaultContentLanguage = "en"
title = "www.open-source-modular.org    "
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Open Source Modular" # Set a different text for the header on the home page
  subtitle = "A collection of well documented synthesizer modules"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  discord = "invite code (https://discord.gg/XXXXXXX)"
  github = "username"
  #name = "Some Person"
  #website = "yourwebsite.com"
  #email = "youremail@domain.com"
  #facebook = "username"
  #gitlab = "username"
  #bitbucket = "username"
  #twitter = "username"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"
  #strava = "userid"

[[menu.main]]
    name = "Project news"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "modules"
    name = "Modules"
    weight = 2

[[menu.main]]
    parent = "modules"
    name = "Diode or"
    url = "module/tile-diode-or"
    weight = 1

[[menu.main]]
    parent = "modules"
    name = "Active multiple"
    url = "module/tile-active-multiple"
    weight = 2

[[menu.main]]
    parent = "modules"
    name = "Passive multiple"
    url = "module/tile-passive-multiple"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
